import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans, Geist, Playwrite_AU_NSW, Kameron } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Variable } from "lucide-react";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter-regular" });
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta-regular",
});
const kameron = Kameron({
  subsets: ["latin"],
  variable: "--font-kameron-regular",
});

const playwrite = Playwrite_AU_NSW({
  variable : "--font-playwrite", 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", kameron.variable,playwrite.variable , inter.variable , jakarta.variable)}>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
