import type { Metadata } from "next";
import {
  Inter,
  Plus_Jakarta_Sans,
  Geist,
  Playwrite_AU_NSW,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import MainLayout from "@/providers/main-layout";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({
  variable: "--font-inter-regular",
  subsets: ["latin"],
});
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
});

const playwrite = Playwrite_AU_NSW({
  variable: "--font-playwrite",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "font-sans",
        geist.variable,
        playwrite.variable,
        inter.variable,
        plusJakartaSans.variable,
      )}
    >
      <body className={`antialiased`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
